### ISSUE TITLE
Can't find file to install

### ISSUE THREAD

**Issue by touchscreen97** [neoxzgen/analog-time-visualizer#1]
``First Step
clone the project and go to the folder and run "npm install" to install the node_modules``

There aren't any file names npm install. Maybe I'm doing something wrong? I am new to this.

**Comment by neoxzgen** [comment]
This App ist created with React https://reactjs.org/docs/create-a-new-react-app.html.
Please make sure you have npm installed in you system https://www.npmjs.com/ or yarn

So when you pull the Project you must go with you Terminal to the Project and run the command "npm install" to install all the dependecies (node_modules) to the project after that you must start it with "npm start"

**Comment by touchscreen97** [comment]
Thank you thins fixed it. I was confused about how to run it.
